[package]
name = "cargo-wix"
description = "Build Windows installers using the Wix Toolset"
version = "0.0.1"
authors = ["Christopher Field <cfield2@gmail.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/volks73/cargo-wix"
documentation = "https://volks73.github.io/cargo-wix"
categories = ["development-tools"]
keywords = ["cargo-subcommand", "installer", "wix-toolset", "wix"]
homepage = "https://github.com/volks73/cargo-wix"
readme = "README.md"

[[bin]]
name = "cargo-wix"
doc = false

[lib]
name = "cargo_wix"

[dependencies]
ansi_term = "0.10"
atty = "0.2"
chrono = "0.4"
clap = "2.28"
log = "0.3"
loggerv = "0.6"
mustache = "0.8"
regex = "0.2"
toml = "0.4"
uuid = { version = "0.5", features = ["v4"] }

