[package]
name = "cargo-wix"
description = "Build Windows installers using the Wix Toolset"
version = "0.1.0"
authors = ["Christopher Field <cfield2@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/volks73/cargo-wix"
documentation = "https://github.com/volks73/cargo-wix"
categories = ["development-tools"]
keywords = ["cargo-subcommand", "installer", "wix-toolset", "wix"]
homepage = "https://github.com/volks73/cargo-wix"
readme = "README.md"

[[bin]]
name = "cargo-wix"

[dependencies]
ansi_term = "0.10"
atty = "0.2"
clap = "2.28"
log = "0.3"
loggerv = "0.6"
toml = "0.4"

