[package]
name = "cargo-wix"
description = "Build Windows installers using the Wix Toolset"
version = "0.0.5"
authors = ["Christopher Field <cfield2@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/volks73/cargo-wix"
documentation = "https://volks73.github.io/cargo-wix"
categories = ["development-tools"]
keywords = ["cargo-subcommand", "installer", "wix-toolset", "wix"]
homepage = "https://github.com/volks73/cargo-wix"
readme = "README.md"

[[bin]]
name = "cargo-wix"
doc = false

[lib]
name = "cargo_wix"

[dependencies]
chrono = "0.4"
env_logger = "0.5"
log = "0.4"
mustache = "0.9"
regex = "1"
semver = "0.9"
termcolor = "1"
toml = "0.4"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
assert_cmd = "0.9"
assert_fs = "0.9"
lazy_static = "1"
predicates = "0.9"
tempfile = "3"

[dependencies.clap]
version = "2"
default-features = false
features = ["suggestions", "vec_map"]

